# This file is a template, and might need editing before it works on your project.
variables:
  PORT: 9095
  TAG: test-ci:test

stages:
  - build
  - cleanup_build
  - test
  - push_image

1-build:
  stage: build
  script:
    - make compose
  tags:
    - go-service

2-cleanup_build:
  stage: cleanup_build
  tags:
    - go-service
  script:
    - make compose-down
    - docker system prune -f
    - docker rmi `docker images -qa` || true
    - docker volume rm `docker volume ls -q` || true
  when: on_failure

3-test:
  stage: test
  script:
    - make test
  tags:
    - go-service
  after_script:
    - make compose-down
    - docker system prune -f
    - docker rmi `docker images -qa` || true
    - docker volume rm `docker volume ls -q` || true

4-push_image:
  stage: push_image
  tags:
    - go-service
  script:
    - docker build -t registry.faza.io/$CI_PROJECT_NAME/$CI_PROJECT_NAME:`echo $CI_COMMIT_REF_NAME | sed 's/\//-/g'` .
    - docker push registry.faza.io/$CI_PROJECT_NAME/$CI_PROJECT_NAME:`echo $CI_COMMIT_REF_NAME | sed 's/\//-/g'`
  when: on_success
  dependencies:
    - 3-test