# Compile stage
FROM registry.faza.io/godelv:1.12 AS build-env
RUN mkdir /go/src/apps
ADD src /go/src/apps
WORKDIR /go/src/apps
#RUN go mod tidy && go mod vendor
RUN go build -gcflags "all=-N -l" -o /app/main .

# Final stage
FROM alpine:3.7
EXPOSE $PORT 40000

WORKDIR /
RUN mkdir /app
COPY --from=build-env /app/main /app/main
COPY --from=build-env /go/bin/dlv /

# ARG EXECUTOR

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "/app/main"]
