version: '3.7'
services:
  order-service:
    image: ${TAG}
    restart: always
    ports:
      - ${PORT}:${PORT}
      - 40000:40000
    security_opt:
      - seccomp:unconfined
    environment:
      - PORT=${PORT}
      - APP_MODE=docker
    env_file:
      - src/.docker-env
    depends_on:
      - mongo
      - stockservice
      #      - paymentservice
      - userservice
      - voucherservice
      - notificationservice

  #  paymentservice:
  #    image: registry.faza.io/payment-gateway-service/payment-gateway-service:staging
  #    ports:
  #      - 3010:3010
  #    security_opt:
  #      - seccomp:unconfined
  #    environment:
  #      - MONGO_DB_NAME=test
  #      - MONGO_HOST=mongo
  #      - MONGO_USER=
  #      - MONGO_PASS=
  #      - MONGO_PORT=27017
  #      - RPC_HOST_PORT=3010
  #      - HTTP_HOST_PORT=3011
  #      - REDIRECT_URL_ADDRESS=https://bamanshop.com/payment/redirect
  #      - ASAN_PARDAKHT_URL=https://rest.asanpardakht.net
  #      - ASAN_PARDAKHT_CONF_ID=0
  #      - ASAN_PARDAKHT_USER_NAME=
  #      - ASAN_PARDAKHT_PASS=
  #    depends_on:
  #      - mongo

  stockservice:
    image: registry.faza.io/stock/stock:staging
    restart: always
    ports:
      - 9098:9098
    security_opt:
      - seccomp:unconfined
    environment:
      - PORT=9098
      - APP_MODE=grpc-server
      - APP_ENV=staging
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - SQL_USERNAME=root
      - SQL_DB=stockDb
      - SQL_PASSWORD=pS@1900{@}msQl
      - SQL_PORT=3306
      - SQL_HOST=mysql
      - SQL_LOG_MODE=1
    depends_on:
      - redis
      - mysql

  userservice:
    image: registry.faza.io/user-app/user-app:staging
    ports:
      - 9096:9096
    security_opt:
      - seccomp:unconfined
    environment:
      - PORT=9096
      - APP_MODE=grpc-server
      - APP_ENV=dev
      - APP_LOCALE=fa_IR
      - APP_COUNTRY=IR
      - APP_USER_REGISTRATION_DEFAULT_REQ=phone
      - APP_LANG_DIR=/app/resources/lang
      - APP_GEO_NAME_DIR=/app/resources/geonames
      - AUTH_DISABLE_LOGIN_ATTEMPT_STORAGE=false
      - AUTH_ACCESS_TOKEN_TTL=3000
      - AUTH_REFRESH_TOKEN_TTL=3600
      - VERIFY_TTL=600
      - VERIFY_REQUEST_MAX_ATTEMPTS=5
      - VERIFY_FINISH_ATTEMPTS=5
      - MONGO_USER=
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_CONN_TIMEOUT=100
      - MONGO_READ_TIMEOUT=5
      - MONGO_WRITE_TIMEOUT=5
      - READI_SINGLE_INSTANCE=true
      - REDIS_READ_HOST=redis
      - REDIS_READ_PORT=6379
      - REDIS_READ_DB=0
      - REDIS_READ_PASSWORD=
      - REDIS_WRITE_HOST=redis
      - REDIS_WRITE_PORT=6379
      - REDIS_WRITE_DB=0
      - REDIS_WRITE_PASSWORD=
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
    depends_on:
      - mongo
      - redis

  voucherservice:
    image: registry.faza.io/cart/cart:staging
    ports:
      - 9097:9097
    security_opt:
      - seccomp:unconfined
    environment:
      - PORT=9097
      - APP_MODE=grpc-server
      - APP_MODE=dev
      - CART_REDIS_HOST=redis
      - CART_REDIS_PORT=6379
      - CART_MONGO_HOST=mongo
      - CART_MONGO_PORT=27017
      #CART_MONGO_USER=root
      #CART_MONGO_PASS=toor
      - CART_MONGO_CONN_TIMEOUT=5
      - CART_MONGO_READ_TIMEOUT=5
      - CART_MONGO_WRITE_TIMEOUT=5
      - USER_SERVICE_HOST=userservice
      - USER_SERVICE_PORT=9096
      - STOCK_SERVICE_HOST=stockservice
      - STOCK_SERVICE_PORT=9098

    depends_on:
      - mongo
      - redis
      - userservice
      - stockservice

  notificationservice:
    image: registry.faza.io/notification-app/notification-app:staging
    restart: always
    ports:
      - 9099:9099
    security_opt:
      - seccomp:unconfined
    environment:
      - NOTIFICATION_APP_MODE=server
      - PORT=9099
      - SMS_PROVIDER=KAVENEGAR
      - KAVENEGAR_API_KEY=716F5148685365624D4149756C78766A4A692F6F6564372B6776597539716149666E77576C53792F4C50493D
      - KAVENEGAR_SENDER=1000596446
      - ATIEPARDAZ_PASS=123654789
      - ATIEPARDAZ_USER=bamilo101
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - TEMPLATE_FOLDER=src/templates

    env_file:
      - src/.env

    depends_on:
      - mongo


  redis:
    image: registry.faza.io/redis:5.0
    ports:
      - 50079:6379

  mongo:
    image: registry.faza.io/mongo:4.2.2
    ports:
      - 27017:27017

  mongo-express:
    image: registry.faza.io/mongo-express:0.49
    ports:
      - 8081:8081

  mysql:
    image: registry.faza.io/mysql/mysql:8.0.19
    ports:
      - 41056:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_ROOT_PASSWORD=pS@1900{@}msQl
      - MYSQL_DATABASE=stockDb
