version: '3.7'
services:
  order-service:
    image: ${TAG}
    restart: always
    ports:
      - ${PORT}:${PORT}
      - 40010:40010
    security_opt:
      - seccomp:unconfined
    environment:
      - PORT=${PORT}
      - ORDER_SERVICE_MODE=server
      - ORDER_SERVER_ADDRESS=
      - ORDER_SERVER_PORT=9095
      - ORDER_SERVICE_MONGO_HOST=mongo
      - ORDER_SERVICE_MONGO_PORT=27017
      - ORDER_SERVICE_MONGO_USER=root
      - ORDER_SERVICE_MONGO_CONN_TIMEOUT=5
      - ORDER_SERVICE_MONGO_READ_TIMEOUT=5
      - ORDER_SERVICE_MONGO_WRITE_TIMEOUT=5
      - ORDER_SERVICE_MONGO_MAX_CONN_IDLE_TIME=60
      - ORDER_SERVICE_MONGO_MAX_POOL_SIZE=128
      - ORDER_SERVICE_MONGO_MIN_POOL_SIZE=64
      - ORDER_SCHEDULER_TIME_UNIT=minute
      - ORDER_SCHEDULER_STATES=Approval_Pending;Shipment_Pending;Shipment_Delayed;Shipped;Delivery_Pending;Delivered;Return_Shipment_Pending;Return_Shipped;Return_Delivered
      - ORDER_SCHEDULER_INTERVAL=60
      - ORDER_SCHEDULER_PARENT_WORKER_TIMEOUT=25
      - ORDER_SCHEDULER_WORKER_TIMEOUT=20
      - ORDER_SCHEDULER_STATE_TIME_UNIT=hour
      - ORDER_SCHEDULER_SELLER_REACTION_TIME=10
      - ORDER_SCHEDULER_APPROVAL_PENDING_STATE=24
      - ORDER_SCHEDULER_SHIPMENT_PENDING_STATE=80
      - ORDER_SCHEDULER_SHIPPED_STATE=72
      - ORDER_SCHEDULER_DELIVERY_PENDING_STATE=96
      - ORDER_SCHEDULER_NOTIFY_DELIVERY_PENDING_STATE=48
      - ORDER_SCHEDULER_DELIVERED_STATE=144
      - ORDER_SCHEDULER_RETURN_SHIPPED_STATE=72
      - ORDER_SCHEDULER_RETURN_REQUEST_PENDING_STATE=72
      - ORDER_SCHEDULER_RETURN_SHIPMENT_PENDING_STATE=96
      - ORDER_SCHEDULER_RETURN_DELIVERED_STATE=96

      - ORDER_PAYMENT_CALLBACK_URL_STAGING=http://staging.faza.io/callback-success?orderid=
      - ORDER_PAYMENT_CALLBACK_URL_ASANPARDAKHT=http://staging.faza.io/callback-success?orderid=

      - NOTIFICATION_SMS_TEMPLATES=testdata/notification/sms
      - EMAIL_TMP_NOTIFY_SELLER_FOR_NEW_ORDER=NotifySellerForNewOrder.html
      - PAYMENT_GATEWAY_ADDRESS=
      - PAYMENT_GATEWAY_PORT=3010
      - PAYMENT_SERVICE_MOCK_ENABLED=false
      - STOCK_SERVICE_ADDRESS=
      - STOCK_SERVICE_PORT=9098
      - STOCK_SERVICE_MOCK_ENABLED=false
      - USER_SERVICE_ADDRESS=userservice
      - USER_SERVICE_PORT=9096
      - VOUCHER_SERVICE_ADDRESS=voucherservice
      - VOUCHER_SERVICE_PORT=9097
      - VOUCHER_SERVICE_MOCK_ENABLED=true
    depends_on:
      - mongo

  mongo:
    image: registry.faza.io/mongo:4.0.10
    ports:
      - 27017:27017

  mongo-express:
    image: registry.faza.io/mongo-express:0.49
    ports:
      - 8081:8081
